[package]
name = "einbocha-playing-cards"
version = "0.1.1"
edition = "2024"
description = "Simple high performance playing cards crate"
license = "MIT OR Apache-2.0"
repository = "https://github.com/einbocha/einbocha-playing-cards"
readme = "README.md"
keywords = ["cards", "playing-cards", "deck", "doppelkopf", "poker"]
categories = ["games", "simulation", "data-structures"]

[dependencies]
